import Header from "./components/Header";
import Footer from "./components/Footer";
import "@/styles/globals.css";

export const metadata = {
  title: "Title",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="bg-base-100">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
